# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Joonho Chang
title: Ph.D. student
email: joonnozx@gmail.com
# email_title: Email (Email title override)
# phone: +82 10-7122-9108
# phone_title: Phone (Phone title override)
# website: https://sites.google.com/view/kvl
# website_title: KNU Vision & Learning Lab

# address:
#   street: IT1 309, 80 Daehak-ro
#   district: Buk-gu
#   city: Daegu
#   country: Korea
#   postal_code: 41566

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
# github_username: 
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: 9bsecQIAAAAJ&hl=ko

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/Junwon.jpeg
about_content: | # this will include new lines to allow paragraphs
  I am an experienced AI and software engineer with expertise in computer vision, time series analysis, and software development. Currently, I am a doctoral candidate in the Department of Artificial Intelligence at Kyungpook National University, conducting research in AI-based medical imaging, time series analysis, and image generation. Additionally, I am proficient in developing models for limited data and enhancing generalization performance by mitigating data imbalance and overfitting problems. With 6 years of experience in AI research and Python, I possess skills in utilizing AI frameworks such as TensorFlow and PyTorch for model development and performance enhancement. Building upon these skills and experience, I have successfully completed numerous national and industrial projects.
  
# You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
#   - Lists
#   - Tables
#   - <a href="google.com">Links</a>
#   - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: EDUCATION
    layout: list
    content:
      - layout: left
        title: Kyungpook National University
        # sub_title: Integrated Master's & Ph.D in Artificial Intelligence, KNU
        # caption: Dec. 2023 - Current, Prof. Heechul Jung
        description: | # this will include new lines to allow paragraphs
          -  Ph.D in Artificial Intelligence, KNU
          - Dec. 2023 – Current, Prof. Heechul Jung
          - Mar. 2021 – Nov. 2023, Prof. Minho Lee

      - layout: left
        title: Kyungpook National University
        # sub_title: B.S. in Mathematics and Electronic Engineering (Double Major), KNU
        # caption: Mar. 2015 - Aug. 2020
        description: | # this will include new lines to allow paragraphs
          - M.S. in Electtronic Engineering (Artificial Intelligence), KNU
          - Mar. 2019 – Feb. 2021, Prof. Minho Lee
          - Thesis: “Adaptive R-CNN with Center Surround Difference for Hemorrhage Segmentation in CT Images”

      - layout: left
        title: Kyungpook National University
        # sub_title: B.S. in Mathematics and Electronic Engineering (Double Major), KNU
        # caption: Mar. 2015 - Aug. 2020
        description: | # this will include new lines to allow paragraphs
          - B.S. in Electtronic Engineering (Signal Processing), KNU
          - Mar. 2015 – Feb. 2019

  - title: PUBLICATION
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **Joonho Chang**, `Inchul Choi1`, & Minho Lee. (2023). PESA R-CNN: Perihematomal Edema Guided Scale Adaptive R-CNN for Hemorrhage Segmentation. (IEEE Journal of Biomedical and Health Informatics, IF:7.7, JCR Top 6%)
      - Changwan Kang, **Joonho Chang**, & Minho Lee (2023). Convolutional Neural Networks for Predicting Mortality Rate and Length of Stay in Intensive Care Unit Patients with Data Imbalance. (Conference of the Society of Medical Informatics)
      - **Joonho Chang** & Minho Lee (2023). HMV-GAN: generate hand bone images in multi-view direction (Brain Engineering Society of Korea)
      - **Joonho Chang** & Minho Lee (2021). Adaptive R-CNN with Center Surround Difference for Hemorrhage Segmentation in CT images (Brain Engineering Society of Korea) 
  
  - title: INTERNATIONAL PATENT
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **Joonho Chang** & Minho Lee. (US) Deep Neural Network-based Cerebral Hemorrhage Diagnosis System. Application (2023), 18/033.063 
      - **Joonho Chang** & Minho Lee. (EPO) Deep Neural Network-based Cerebral Hemorrhage Diagnosis System. Application (2023), 21883174.1 
      - **Joonho Chang** & Minho Lee. (PCT) Cerebral Hemorrhage Diagnosis System Using Deep Neural Network. Application (2021), PCT/KR2021/014543 
      
  - title: DOMESTIC PATENT
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **Joonho Chang**, Jalali Amin, Minho Lee. Apparatus and method for predicting length of stay and mortality rate of patients in intensive care unit. Granted (2023), 10-2600493-00-00 / Applcation (2023), 10-2023-0036401
      - **Joonho Chang**, Jalali Amin, Jonghong Kim, Jeongho Hong, & Minho Lee. Patient status analysis system in the intensive care unit based on deep neural network. Granted (2023), 10-2598101-00-00 / Applcation (2022), 10-2022-0078274 
      - **Joonho Chang** & Minho Lee). Cerebral hemorrhage diagnosis system using deep neural network. Granted(2023), 10-2528727-00-00 / Application (2020), 10-2020-0137614 
      - **Joonho Chang**, Doyoung Kwon, Jinhan Lee, Changuk Oh, Donghyun Kin, & Minho Lee. Apparatus and method for diagnosis of atypical, femur fracture based on artificial intelligence. Application (2024), 10-2024-0012171 
      - **Joonho Chang** & Minho Lee. 3D CT image generation device and method based on Generative Adversarial Network. Application (2023), 10-2023-0188097 
  
  - title: SOFTWARE
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Mortality prediction model for intensive care unit patients with neurological disorder. (2023), ASSET_0009888 
      - Length of Stay prediction model for intensive care unit patients with neurological disorder. (2023), ASSET_0009889 

  - title: PROJECTS # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: National Research Foundation of Korea 
        description: | # this will include new lines to allow paragraphs
          - July. 2022 – Jan. 2023. AI programming education utilizing challenge-based pair-programming
          - July. 2022 – Current. Establishing a world-first medical technology commercialization platform based on K-Leading Tech to secure global competitiveness.
          - June. 2022 – Current. Deciphering traditional records using deep learning for the construction of a virtual Confucian Academy in the metaverse          
          - Apr. 2021 – Dec. 2023. Building specialized big data for critical care patients and developing an AI-based Clinical Decision Support System (CDSS)
          - Mar. 2021 – Feb 2023. Artificial Intelligence agent that Generates, Utilizes, and Augments Knowledge Through Conversation 
          - Apr. 2020 – Dec. 2023. Development of AI imaging diagnostic technology for integration into medical devices
          - Nov. 2020 – July. 2021. Recognition and deciphering of traditional record characters using advanced deep learning technology.
          - Jan. 2020 – Mar. 2021. Development of intelligent SW technology for medical data analysis.
          - May. 2019 – Dec. 2020. Research and development of intelligent interaction technology capable of understanding user intent and context.
          
          
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Agency for Defense Development
        description: | # this will include new lines to allow paragraphs
          - Dec. 2019 - Dec. 2020. Research on automatic generation of report sentences through situation awareness (MX-41)
      
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: LG Electronics Inc.
        description: | # this will include new lines to allow paragraphs
          - Jan. 2024 - Current. Development of a Universal Model for Refrigerant Shortage Classification Using Artificial Intelligence.
  
  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

  #     Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
